
  services:
    mysqldb:
      image: mysql:latest
      environment:
        MYSQL_DATABASE: fxdeals_tracker
        MYSQL_USER: fXDealUser
        MYSQL_PASSWORD: fXDealUser11
        MYSQL_ROOT_PASSWORD: root
      ports:
        - "3306:3306"

    application:
      depends_on:
        - mysqldb
      build: .
      ports:
        - "8080:8080"
      environment:
       spring.datasource.url: jdbc:mysql://mysqldb:3306/fxdeals_tracker
       spring.datasource.username: fXDealUser
       spring.datasource.password: fXDealUser11